 enum GAME_STATES {
   GAME_MENU GAME_POINT GAME_PLAYING GAME_SERVING GAME_SERVE , , , , ,
 }
 enum BALL_STATES {
   SERVE THROWING SERVING PLAYING STOPPED OUT , , , , , ,
 }
 enum PLAYER_STATES {
   SERVING RECIEVING PLAYING AIM UP LEFT DOWN RIGHT , , , , , , , ,
 }
